name: cooking_book
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  provider: ^6.1.2

dev_dependencies:
  hive_generator: ^1.1.0
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/img/
  fonts:
    - family: Sweet Mavka Script
      fonts:
        - asset: assets/fonts/Sweet-Mavka-Script.otf
    - family: pershotravneva55-regular
      fonts: 
        - asset: assets/fonts/pershotravneva55-regular.ttf
