name: coffe_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Rosarivo
      fonts:
        - asset: assets/fonts/Rosarivo-Italic.ttf
        - asset: assets/fonts/Rosarivo-Regular.ttf
          weight: 400
  assets:
    - assets/svg/
    - assets/png/